// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpmgpxpmlyfrmtwdipzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwbWdweHBtbHlmcm10d2RpcHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA4MzcwMTIsImV4cCI6MjA1NjQxMzAxMn0.ag4cPNWkiOKX-rhSVl38Xwft_enuMOjbochXYRwJ_oE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);